env:
  BUILD_CACHE_PATH: '.gradle

    ./bin

    **/bin

    **/build

    '
  GLOBAL_CACHE_KEY: gradle-m2-java-11
  GLOBAL_CACHE_PATH: '~/.gradle

    ~/.m2

    '
  GLOBAL_CACHE_RESTORE_KEYS: 'gradle-m2-java-

    gradle-m2

    '
  REPORTS_LOCATIONS: './*/build/reports ./*/*/build/reports ./*/*/*/build/reports

    '
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Build Information
      run: echo Building a '${{ github.event_name }}' for target '${{ github.ref }}'.
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}

          '
    - continue-on-error: true
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      name: Clean
      run: ./gradlew clean ${{env.GRADLE_OPTS}}
    - continue-on-error: true
      name: Compile & Checkstyle
      run: ./gradlew jar compileTest checkstyleMain checkstyleTest --parallel ${{env.GRADLE_OPTS}}
    - continue-on-error: true
      name: Tar Reports
      run: tar --use-compress-program zstd -cf reports-${{github.job}}.tzst `echo
        ${{env.REPORTS_LOCATIONS}}`
    - continue-on-error: true
      name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.job}}-reports
        path: reports-${{github.job}}.tzst
        retention-days: 4
  build_and_test_complete:
    name: CI Complete
    needs:
    - build
    - integration
    - unit_other
    - unit_segment_store
    - unit_storage
    - unit_controller
    - unit_client
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Check Build Status
      run: echo Build, static analysis, unit and integration tests successful.
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - continue-on-error: true
      name: Download code coverage reports
      uses: actions/download-artifact@v2
    - continue-on-error: true
      name: Untar reports
      run: ( ls */reports-*.tzst | xargs -n1 tar --use-compress-program zstd --keep-newer-files
        -xf )
    - continue-on-error: true
      name: Upload to Codecov
      uses: codecov/codecov-action@v1
  integration:
    name: Integration Tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}-${{github.run_id}}

          ${{github.ref}}

          '
    - continue-on-error: true
      name: Integration Tests
      run: ./gradlew test:integration:test --parallel ${{env.GRADLE_OPTS}}
  snapshot:
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref,
      'refs/heads/r0.') || startsWith(github.ref, 'refs/heads/r1.')) }}
    name: Publish snapshot packages
    needs:
    - build_and_test_complete
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}-${{github.run_id}}

          ${{github.ref}}

          '
    - continue-on-error: true
      name: Assemble
      run: ./gradlew assemble --parallel ${{env.GRADLE_OPTS}}
    - continue-on-error: true
      name: Publish to GitHub Packages
      run: ./gradlew publish -PpublishUrl=https://maven.pkg.github.com/${{github.repository}}
        -PpublishUsername=${{github.actor}} -PpublishPassword=${{secrets.GITHUB_TOKEN}}
        ${{env.GRADLE_OPTS}}
  snapshot_docs:
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref,
      'refs/heads/r0.') || startsWith(github.ref, 'refs/heads/r1.')) }}
    name: Upload Docs Snapshot
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}-${{github.run_id}}

          ${{github.ref}}

          '
    - continue-on-error: true
      name: Build MkDocs and Javadocs
      run: './gradlew -PenableMkdocs=true -PsimpleSnapshot=true mkdocsBuild javadocs
        ${{env.GRADLE_OPTS}}

        '
    - continue-on-error: true
      env:
        KNOWN_HOST: ${{ secrets.PRAVEGA_IO_KNOWN_HOST }}
        SSH_KEY: ${{ secrets.PRAVEGA_IO_SSH_KEY }}
      name: Upload MkDocs and Javadocs snapshot
      run: "mkdir ~/.ssh\necho \"$KNOWN_HOST\" >> ~/.ssh/known_hosts\necho \"$SSH_KEY\"\
        \ > ~/pravegaio.pem\nchmod 400 ~/pravegaio.pem\nVERSION=$(grep pravegaVersion\
        \ gradle.properties | sed 's/pravegaVersion=//')\ncd documentation/generated/$VERSION\n\
        ssh -i ~/pravegaio.pem ubuntu@cncf.pravega.io \"rm -rf /var/www/pravega.io/docs/v$VERSION\
        \ && mkdir -p /var/www/pravega.io/docs/v$VERSION\"\ntar cf - * | ssh -i ~/pravegaio.pem\
        \ ubuntu@cncf.pravega.io \"cd /var/www/pravega.io/docs/v$VERSION && tar xvf\
        \ -\"\nssh -i ~/pravegaio.pem ubuntu@cncf.pravega.io \"mkdir /var/www/pravega.io/docs/v$VERSION/javadoc/clients\"\
        \ncd ../../../build/javadocs/\ntar cf - * | ssh -i ~/pravegaio.pem ubuntu@cncf.pravega.io\
        \ \"cd /var/www/pravega.io/docs/v$VERSION/javadoc/clients && tar xvf -\"\n\
        echo -e \\\\nDocs site updated at https://cncf.pravega.io/docs/v$VERSION\n\
        if [ \"${{ github.ref }}\" == 'refs/heads/master' ]; then\n  ssh -i ~/pravegaio.pem\
        \ ubuntu@cncf.pravega.io \"rm /var/www/pravega.io/docs/snapshot && cd /var/www/pravega.io/docs\
        \ && ln -s v$VERSION snapshot\"\n  echo Symlink updated at https://cncf.pravega.io/docs/snapshot\n\
        fi\n"
  unit_client:
    name: Client Unit Tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}-${{github.run_id}}

          ${{github.ref}}

          '
    - continue-on-error: true
      name: Unit tests
      run: ./gradlew client:test shared:protocol:test shared:security:test common:test
        test:testcommon:test --parallel ${{env.GRADLE_OPTS}}
    - continue-on-error: true
      name: Tar Reports
      run: tar --use-compress-program zstd -cf reports-${{github.job}}.tzst `echo
        ${{env.REPORTS_LOCATIONS}}`
    - continue-on-error: true
      if: always()
      name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.job}}-reports
        path: reports-${{github.job}}.tzst
        retention-days: 4
  unit_controller:
    name: Controller Unit Tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}-${{github.run_id}}

          ${{github.ref}}

          '
    - continue-on-error: true
      name: Controller Unit tests
      run: ./gradlew controller:test shared:controller-api:test --parallel ${{env.GRADLE_OPTS}}
    - continue-on-error: true
      name: Tar Reports
      run: tar --use-compress-program zstd -cf reports-${{github.job}}.tzst `echo
        ${{env.REPORTS_LOCATIONS}}`
    - continue-on-error: true
      if: always()
      name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.job}}-reports
        path: reports-${{github.job}}.tzst
        retention-days: 4
  unit_other:
    name: All Other Unit Tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}-${{github.run_id}}

          ${{github.ref}}

          '
    - continue-on-error: true
      name: Static analysis tests
      run: './gradlew rat spotbugsMain spotbugsTest --parallel ${{env.GRADLE_OPTS}}

        '
    - continue-on-error: true
      name: Unit tests
      run: './gradlew test -x client:test -x shared:protocol:test -x shared:security:test
        -x common:test -x test:testcommon:test -x controller:test -x shared:controller-api:test
        -x test:integration:test -x bindings:test -x segmentstore:storage:impl:test
        -x segmentstore:storage:test -x segmentstore:server:host:test -x segmentstore:server:test
        --parallel ${{env.GRADLE_OPTS}}

        '
    - continue-on-error: true
      name: Tar Reports
      run: tar --use-compress-program zstd -cf reports-${{github.job}}.tzst `echo
        ${{env.REPORTS_LOCATIONS}}`
    - continue-on-error: true
      if: always()
      name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.job}}-reports
        path: reports-${{github.job}}.tzst
        retention-days: 4
  unit_segment_store:
    name: Segment Store Unit Tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}-${{github.run_id}}

          ${{github.ref}}

          '
    - continue-on-error: true
      name: Segment Store Unit tests
      run: './gradlew segmentstore:server:test segmentstore:server:host:test bindings:test
        --parallel ${{env.GRADLE_OPTS}}

        '
    - continue-on-error: true
      name: Tar Reports
      run: tar --use-compress-program zstd -cf reports-${{github.job}}.tzst `echo
        ${{env.REPORTS_LOCATIONS}}`
    - continue-on-error: true
      if: always()
      name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.job}}-reports
        path: reports-${{github.job}}.tzst
        retention-days: 4
  unit_storage:
    name: Storage Unit Tests
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle & Maven Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{env.GLOBAL_CACHE_KEY}}
        path: ${{env.GLOBAL_CACHE_PATH}}
        restore-keys: ${{env.GLOBAL_CACHE_RESTORE_KEYS}}
    - continue-on-error: true
      name: Build Output Cache
      uses: actions/cache@v2.1.0
      with:
        key: ${{github.ref}}-${{github.run_id}}-${{github.job}}
        path: ${{env.BUILD_CACHE_PATH}}
        restore-keys: '${{github.ref}}-${{github.run_id}}

          ${{github.ref}}

          '
    - continue-on-error: true
      name: Segment Store Unit tests
      run: './gradlew segmentstore:storage:test segmentstore:storage:impl:test --parallel
        ${{env.GRADLE_OPTS}}

        '
    - continue-on-error: true
      name: Tar Reports
      run: tar --use-compress-program zstd -cf reports-${{github.job}}.tzst `echo
        ${{env.REPORTS_LOCATIONS}}`
    - continue-on-error: true
      if: always()
      name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.job}}-reports
        path: reports-${{github.job}}.tzst
        retention-days: 4
name: build
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
